### ISSUE TITLE
invalid syntax at docker-compose run

### ISSUE THREAD

**Issue by yuhan1010** [worried-networking/tlscontact-appointment-finder#13]
`
docker-compose run -d selenium && sleep 20
`
`
                   ^
`
`
SyntaxError: invalid syntax
`

I installed all of the packages including docker-compose, but it seems not working, and I found that there is no command named "run".

could anyone help me to fix it by any chance? :)

**Comment by andrey-yantsen** [comment]
@yuhan1010 erm... can you show me all of what you're doing?

It looks like you're trying to run the command from the python REPL...

**Comment by yuhan1010** [comment]
> 
sry to disturb u, bro, and thx for helping.

yeah, it's my fault. I used python to run these commands this morning (the below one).
<img width="1249" alt="截屏2023-02-20 下午6 19 25" src="https://user-images.githubusercontent.com/59042211/220177372-c8a1596c-85d3-45c2-94a6-e69897effe3b.png">

So I tried using shell command to run them, but also failed.
<img width="580" alt="image" src="https://user-images.githubusercontent.com/59042211/220177786-2948c500-aeee-481d-bd99-5ce7460138b8.png">

I have no idea which part I made mistakes. thx for helping.

**Comment by andrey-yantsen** [comment]
Do you have docker installed and running? Please confirm that `docker info` can be executed successfully.

**Comment by yuhan1010** [comment]
> Do you have docker installed and running? Please confirm that `docker info` can be executed successfully.

Thx for helping. I installed the desktop one, and it works.

But the command said there is a syntax error about telegram chat id. I'm sure the id is obtained following your tutorial.

![image](https://user-images.githubusercontent.com/59042211/220189074-a7c574da-516b-4caf-8431-2e612f7776da.png)

**Comment by andrey-yantsen** [comment]
You need to replace whole arguments from the documentation. E.g. `<TELEGRAM_CHAT_ID>` must be replaced with the correct id; no braces should be left.

**Comment by yuhan1010** [comment]
> You need to replace whole arguments from the documentation. E.g. `<TELEGRAM_CHAT_ID>` must be replaced with the correct id; no braces should be left.

Cheers bro. I fix all of the probs. Just wait for the account frozen countdown :(

thx for helping.
